name: Integration test

on: [pull_request]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Integration Test
    runs-on: ubuntu-latest
    env:
      IS_GITHUB_ACTION: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: sudo apt update && sudo apt install -y jq
      - run: cargo install cargo-generate
      - run: yarn install
      - run: yarn build
      - run: scripts/start-local-node.sh
      - run: yarn test:integration
